#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}
$app = new Symfony\Component\Console\Application(
    'Forge Connect', '1.2.0'
);
$app->add(new LKDevelopment\ForgeConnect\Commands\RegisterCommand());
$app->add(new LKDevelopment\ForgeConnect\Commands\ListServersCommand());
$app->add(new LKDevelopment\ForgeConnect\Commands\ConnectToServerCommand());
$app->run();